### Logistic Regression with Boosting

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
# Read the data from the file train.csv
df = pd.read_csv('train.csv')
data_matrix = np.array(df.values)

# Drop the first column (id)
data_matrix = np.delete(data_matrix, 0, 1)

# Display as a table
df_train = pd.DataFrame(data_matrix)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,4087,4088,4089,4090,4091,4092,4093,4094,4095,4096
0,0.0,0.0,1.272801,0.290501,0.581446,0.0,0.0,0,0.0,0.0,...,1.645888,0.86964,0.302432,0.953719,0.022545,0.498048,0.0,0.034988,0.692382,Orange_Ripe
1,0.0,0.0,1.542096,0.0,0.896557,0.049978,0.0,0,0.117847,0.0,...,1.50422,0.622686,0.588427,0.524415,0.305426,0.386204,0.0,0.0,0.668196,Banana_Ripe
2,0.0,0.0,1.098595,0.571866,0.500355,0.0,0.0,0,0.493137,0.0,...,1.169341,0.913239,0.064404,0.53127,0.0,0.471604,0.0,0.0,0.65825,Mango_Raw
3,0.0,0.101666,1.159194,0.599216,0.893206,0.0,0.200139,0,0.645675,0.0,...,0.560686,1.243676,0.432523,0.701881,0.0,0.589985,0.0,0.0,0.591165,Leeche_Raw
4,0.0,0.0,1.178603,0.362568,0.577602,0.0,0.0,0,0.079862,0.0,...,1.206032,0.736831,0.345906,0.878515,0.119,0.261441,0.0,0.0,0.458905,Mango_Ripe

In [3]:
# Opening the test file for the test data
df_test = pd.read_csv('test.csv')
data_matrix_test = np.array(df_test.values)

# Drop the first column (id)
data_matrix_test = np.delete(data_matrix_test, 0, 1)

# Display as a table
df_test = pd.DataFrame(data_matrix_test)
df_test.head()

,0,1,2,3,4,5,6,7,8,9,...,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095
0,0.0,0.000000,0.908889,0.251257,0.662262,0.042495,0.000000,0.0,0.964784,0.0,...,0.694072,1.146161,1.483842,0.717836,0.472616,0.000000,0.488022,0.0,0.0,0.655670
1,0.0,0.000000,1.191055,0.407350,0.441898,0.000000,0.334858,0.0,0.295357,0.0,...,0.273436,1.466932,0.940850,0.470344,1.032085,0.000000,0.654070,0.0,0.0,0.614493
2,0.0,0.261903,0.992782,0.301102,0.636006,0.009558,0.009448,0.0,0.974949,0.0,...,0.000000,0.769983,0.834360,0.369656,1.000858,0.431571,0.361993,0.0,0.0,0.392158
3,0.0,0.000000,1.352401,0.346003,0.401412,0.000000,0.000000,0.0,0.450667,0.0,...,0.339935,1.325595,0.981124,0.486731,0.747392,0.000000,0.300671,0.0,0.0,0.628365
4,0.0,0.000000,1.114281,0.696140,0.121505,0.000000,0.000000,0.0,0.591384,0.0,...,0.093661,0.875113,0.360689,0.659230,0.546044,0.000000,0.427255,0.0,0.0,0.835671

In [4]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data_matrix[:, :-1], data_matrix[:, -1], test_size=0.2, random_state=42)

# Create a logistic regression model
log_reg = LogisticRegression(max_iter=2000)

# Fit the model to the training data
log_reg.fit(X_train, y_train)

# Predict the labels of the test data
y_pred = log_reg.predict(X_test)

# Calculate the accuracy of the model
accuracy = np.sum(y_pred == y_test) / len(y_test)

print('Accuracy: ', accuracy)

Accuracy:  0.7868852459016393

In [14]:
# Create a Gradient Boosting model
from sklearn.ensemble import GradientBoostingClassifier

# Create a Gradient Boosting model
gb = GradientBoostingClassifier(n_estimators=20, learning_rate=0.05, max_features=4, max_depth=27, random_state=0)

# Fit the model to the training data
gb.fit(X_train, y_train)

# Predict the labels of the test data
y_pred = gb.predict(X_test)

# Calculate the accuracy of the model
accuracy = np.sum(y_pred == y_test) / len(y_test)

print('Accuracy: ', accuracy)

Accuracy:  0.5